config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'

  #resources :articles

  root 'welcome#index'

  resources :articles do
    resources :comments
  end

  resources :users do
    resources :articles
  end

  namespace :api do 
    namespace :v1 do 
      #resources :users, only: [:index, :create, :show, :update, :destroy] 
      resources :users, only: [:index] 
    end 
  end

end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments
  validates :title, presence: true,
                  length: {minimum: 5}
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :articles
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, 
         :validatable, :jwt_authenticatable, jwt_revocation_strategy: Devise::JWT::RevocationStrategies::Null

end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ActionController::Base
  # tried to extend extending Metal but had some issues, so just doing base for now
  protect_from_forgery with: :null_session

  before_action :destroy_session
  before_filter :authenticate_user!

  def destroy_session 
    request.session_options[:skip] = true 
  end 

end 

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::V1::BaseController 

  # this is just some bullshit to return
  def index
    render json: User.all # don't actually do that ; )
  end 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  http_basic_authenticate_with name: "dhh", password: "secret", except: [:index, :show]
  http_basic_authenticate_with name: "dhh", password: "secret", only: :destroy

  def new
   @article = Article.new 
  end

  def index
    @articles = Article.all
  end

  def create
    # render plain: params[:articlez].inspect
    @article = Article.new(article_params)
    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def edit
    @article = Article.find((params[:id]))

  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path
  end

  def show
    @article = Article.find(params[:id])
    p @article
    @article
  end


  private
  def article_params
    params.require(:article).permit(:title, :text)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    #redirect_to article_path(@article)
    redirect_to @article
  end

  private

  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/jwt_wrapper.rb
# Helper module for you to use on your app and in your Strategy
# Don't add "Helper" to its name and rails won't load it has a view helper module.
# "app/helpers/jwt_wrapper.rb"

module JWTWrapper
	extend self

	def encode(payload, expiration = nil)
		expiration ||= Rails.application.secrets.jwt_expiration_hours

		payload = payload.dup
		payload['exp'] = expiration.to_i.hours.from_now.to_i

		JWT.encode payload, Rails.application.secrets.jwt_secret
	end

	def decode(token)
		begin
			decoded_token = JWT.decode token, Rails.application.secrets.jwt_secret

			decoded_token.first
		rescue
			nil
		end
	end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= form_for :article,  url: article_path(@article), method: :patch do |f| %>

  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <% pluralize(@article.errors.count, "error") %>
          prohibited this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


   <p>
     <%= f.label :title %>
     <%= f.text_field :title %>
   </p>

   <p>
     <%= f.label :text%>
     <%= f.text_area :text %>
   </p>

   <p>
     <%= f.submit %>
   </p>
  <% end %>

<%= link_to 'Back', articles_path %> 

app/views/articles/index.html.erb
<h1>Listing Articles</h1>
<%= link_to "New Article", new_article_path %>
<table>
  <tr>
    <th> Title </th>
    <th> Text </th>
  </tr>

  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td> 
      <td><%= article.text %></td> 
      <td><%= link_to 'Show', article_path(article) %></td>
      <td><%= link_to 'Edit', edit_article_path(article) %></td>
      <td><%= link_to 'Delete', article_path(article), method: :delete, data: {confirm: "Are you sure?'"} %></td>
    </tr>
    <% end %>
</table>

app/views/articles/new.html.erb
<h1> New Article </h1>

<%= form_for :article, url: articles_path do |f| %>

  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %>
          prohibited this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/articles/show.html.erb
<p>
  <strong> Title: </strong>
  <%= @article.title %>
</p>
<p>
  <strong> Text: </strong>
  <%= @article.text %>
</p>

<h2>Comments</h2>
<% @article.comments.each do |comment| %>
  <p>
    <strong>Commenter</strong>
    <%= comment.commenter %>
  </p>
  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>
<% end %>

<h2>Add a comment:</h2>
<%= form_for([@article ,@article.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>

  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Edit', edit_article_path(@article) %>
<%= link_to 'Back', articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

<%= link_to 'My Blog', controller: 'articles' %><br>
<%= link_to 'My Blog', articles_path %>

<h1>Welcome !</h1>
<p><%= @user %></p>

<p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
</p>

<h1>Welcome! Now, you can <%= link_to 'Log Out', destroy_user_session_url, method: :delete %></h1>